# Generated by Django 4.2.4 on 2023-08-31 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airport",
            options={},
        ),
    ]
