# Generated by Django 4.2.4 on 2023-09-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0005_alter_ticket_flight"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"]},
        ),
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
